import './globals.css'
import { Inter } from 'next/font/google'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { NextSession } from '@/functions/NextSession'
import TabBar from '@/components/tabbar'
const inter = Inter({ subsets: ['latin'] })
import { mainUser } from '@/functions/NextSession'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
          {(mainUser==null)?<TabBar/>:null}
        </body>
    </html>
  )
}
