import './globals.css'
import { Inter } from 'next/font/google'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import SideNav from '@/components/sidnav'
import BottomNav from '@/components/bottom-nav'
import MaxWidthWrapper from '@/components/maxwithwrapper'
import { AuthContextProvider } from '@/context/authcontext'
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthContextProvider>
      <MaxWidthWrapper>
    
          <div className="flex">
            <SideNav />
            <main className="flex-1">{children}</main>
          </div>
    
        </MaxWidthWrapper>
        <BottomNav/>
        </AuthContextProvider>
        </body>
    </html>
  )
}
